version: '3.3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      supernetwork:
       ipv4_address: 172.20.0.5
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container
    networks:
      supernetwork:
        ipv4_address: 172.20.0.6
    depends_on:
      - postgres


networks:
  supernetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
    postgres:
