version: '3.3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./ca/server.crt:/var/lib/postgresql/server.crt
       - ./ca/server.key:/var/lib/postgresql/server.key
    ports:
      - "5432:5432"
    networks:
      supernetwork:
       ipv4_address: 174.20.0.5
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_container
    networks:
      supernetwork:
        ipv4_address: 174.20.0.6
    depends_on:
      - postgres


networks:
  supernetwork:
    ipam:
      config:
        - subnet: 174.20.0.0/24

volumes:
    postgres: